// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyS6_L17wy2ro20r1hbPLBRxpsQOM6gIU',
    appId: '1:1090182052879:web:d79639ad9c82f139a2b77a',
    messagingSenderId: '1090182052879',
    projectId: 'detector-ff205',
    authDomain: 'detector-ff205.firebaseapp.com',
    storageBucket: 'detector-ff205.firebasestorage.app',
    measurementId: 'G-PTV7CKE34F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9V2sbM6nNEy1OWTtl2mCtZMuI16VOrAM',
    appId: '1:1090182052879:android:537431881bc88feaa2b77a',
    messagingSenderId: '1090182052879',
    projectId: 'detector-ff205',
    storageBucket: 'detector-ff205.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYpJYcLyuwN2ZwnMAEDbDypgGQwozk8IU',
    appId: '1:1090182052879:ios:025fe53505eb2cf1a2b77a',
    messagingSenderId: '1090182052879',
    projectId: 'detector-ff205',
    storageBucket: 'detector-ff205.firebasestorage.app',
    iosBundleId: 'com.example.detector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYpJYcLyuwN2ZwnMAEDbDypgGQwozk8IU',
    appId: '1:1090182052879:ios:025fe53505eb2cf1a2b77a',
    messagingSenderId: '1090182052879',
    projectId: 'detector-ff205',
    storageBucket: 'detector-ff205.firebasestorage.app',
    iosBundleId: 'com.example.detector',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyS6_L17wy2ro20r1hbPLBRxpsQOM6gIU',
    appId: '1:1090182052879:web:5641fac6e94ca3f1a2b77a',
    messagingSenderId: '1090182052879',
    projectId: 'detector-ff205',
    authDomain: 'detector-ff205.firebaseapp.com',
    storageBucket: 'detector-ff205.firebasestorage.app',
    measurementId: 'G-0G5SYSKW7N',
  );
}
