name: detector
description: "Microplastic Detector App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  google_sign_in: ^7.2.0
  shared_preferences: ^2.2.2

  # State Management
  provider: ^6.1.1

  # Local Storage
  #shared_preferences: ^2.2.2

  # UI Components
  cupertino_icons: ^1.0.6

  # Additional useful packages
  geolocator: ^14.0.2
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  # Add your app icon and other assets here
  # assets:
  #   - images/
  
  # Add custom fonts here
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
